export const FIELD_ITEM_FETCHED = "FIELD_ITEM_FETCHED";
export const FIELD_ITEM_DELETE = "FIELD_ITEM_DELETE";
export const ADD_FIELD_ITEM = "ADD_FIELD_ITEM";
export const EDIT_FIELD_ITEM = "EDIT_FIELD_ITEM";
export const FIELD_ITEM_INITIAL_VALUES = "FIELD_ITEM_INITIAL_VALUES";





