export const GET_PLAYER = "GET_PLAYER";
export const EDIT_PLAYER = "EDIT_PLAYER";
export const PLAYER_INITIAL_VALUES = "PLAYER_INITIAL_VALUES";
export const ADD_PLAYER = "ADD_PLAYER";
export const DELETE_PLAYER = "DELETE_PLAYER";
