export const SCHEDULING_HORARY = "SCHEDULING_HORARY";
export const SCHEDULING_INITIAL_VALUES = "SCHEDULING_INITIAL_VALUES";
export const SCHEDULING_SHOW = "SCHEDULING_SHOW";
export const SCHEDULING_TICKET = "SCHEDULING_TICKET";